version: '3.7'

services:
  app:
    container_name: deloitte_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - REACT_APP_API_URI=http://localhost:8082/rest/